output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}
/* imendozah
output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}*/

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.aws_auth_configmap_yaml
}

output "region" {
  description = "AWS region."
  value       = var.region
}

output "node_groups" {
  description = "Outputs from node groups"
  value       = module.eks.eks_managed_node_groups
}

//
//output "domain_arn" {
//  value       = module.elasticsearch.domain_arn
//  description = "ARN of the Elasticsearch domain"
//}
//
//output "domain_id" {
//  value       = module.elasticsearch.domain_id
//  description = "Unique identifier for the Elasticsearch domain"
//}
//
//output "domain_endpoint" {
//  value       = module.elasticsearch.domain_endpoint
//  description = "Domain-specific endpoint used to submit index, search, and data upload requests"
//}
//
//output "kibana_endpoint" {
//  value       = module.elasticsearch.kibana_endpoint
//  description = "Domain-specific endpoint for Kibana without https scheme"
//}
//
//output "domain_hostname" {
//  value       = module.elasticsearch.domain_hostname
//  description = "Elasticsearch domain hostname to submit index, search, and data upload requests"
//}
//
//output "kibana_hostname" {
//  value       = module.elasticsearch.kibana_hostname
//  description = "Kibana hostname"
//}
//
//output "elasticsearch_user_iam_role_name" {
//  value       = module.elasticsearch.elasticsearch_user_iam_role_name
//  description = "The name of the IAM role to allow access to Elasticsearch cluster"
//}
//
//output "elasticsearch_user_iam_role_arn" {
//  value       = module.elasticsearch.elasticsearch_user_iam_role_arn
//  description = "The ARN of the IAM role to allow access to Elasticsearch cluster"
//}
